export enum CertificateTypeEnum {
  BOAT_LICENSE = "BOAT_LICENSE",
  DRIVER_LICENSE = "DRIVER_LICENSE",
  PORT_PILOT = "PORT_PILOT",
  SEA_PEOPLE = "SEA_PEOPLE",
  WORKING_ELIGIBILITY = "WORKING_ELIGIBILITY",
  DEEP_SEA_DIVER = "DEEP_SEA_DIVER",
  UNDERWATER_WORKER = "UNDERWATER_WORKER",
  FIRST_INSTANCE_MEDICAL_COMMISSION = "FIRST_INSTANCE_MEDICAL_COMMISSION",
  SCUBA_DIVER = "SCUBA_DIVER", //TODO da far aggiungere al modello
  ANNUAL_DRUG_REGISTER = "ANNUAL_DRUG_REGISTER",
  DISINFECTION_EXEMPTION = "DISINFECTION_EXEMPTION",
  DRINKING_WATER_BOXES = "DRINKING_WATER_BOXES",
  DRUG_REGISTER_RELEASE = "DRUG_REGISTER_RELEASE",
  DRUGS_DESTRUCTION = "DRUGS_DESTRUCTION",
  FOOD_BUSINESS = "FOOD_BUSINESS",
  FREE_HEALTHCARE_PRACTICE = "FREE_HEALTHCARE_PRACTICE",
  MEDICAL_GOODS_OR_WASTE = "MEDICAL_GOODS_OR_WASTE",
  MEDICINE_BOX = "MEDICINE_BOX",
  NARCOTIC_REPLENISHMENT = "NARCOTIC_REPLENISHMENT",
  SANITATION_EXEMPTION = "SANITATION_EXEMPTION"
}
